[package]
name = "codepage-rs"
version = "0.2.2"
edition = "2024"
license = "MIT"
categories = ["encoding"]
keywords = ["codepage-437", "codepage", "encoding"]
readme = "README.md"
authors = ["Fae"]
description = "A tiny crate for codepage-437 encoding."
repository = "https://github.com/fhupp/codepage-rs/"

[features]
default = ["std"]
# Disables #![no_std] and adds a few std traits
std = []
# Adds some bytemuck traits
bytemuck = ["dep:bytemuck"]

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"], optional = true }

[lints.clippy]
cargo = { level = "warn", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
doc_broken_link = "deny"
doc_markdown = "deny"
doc_link_code = "deny"
doc_comment_double_space_linebreaks = "deny"
empty_docs = "deny"
doc_paragraphs_missing_punctuation = "deny"
