[package]
name = "codepage-rs"
version = "0.1.1"
edition = "2024"
license = "MIT"
categories = ["encoding"]
keywords = ["codepage-437", "codepage", "encoding"]
readme = "README.md"
description = "A tiny crate for codepage-437 encoding."
repository = "https://github.com/Homomorphism-of-H/codepage-rs/"

[features]
default = ["std"]
std = []

[lints.clippy]
cargo = { level = "warn", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
doc_broken_link = "deny"
doc_markdown = "deny"
doc_link_code = "deny"
doc_comment_double_space_linebreaks = "deny"
empty_docs = "deny"
doc_paragraphs_missing_punctuation = "deny"
